function createfigure(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9, cdata10, cdata11, cdata12, cdata13, cdata14, cdata15, cdata16, cdata17, cdata18, cdata19, cdata20, cdata21, cdata22, cdata23, cdata24, cdata25, cdata26, cdata27, cdata28, cdata29, cdata30, cdata31, cdata32, cdata33, cdata34, cdata35, cdata36, cdata37, cdata38, cdata39, cdata40, cdata41, cdata42, cdata43, cdata44, cdata45, cdata46, cdata47, cdata48, cdata49, cdata50, cdata51, cdata52, cdata53)
%CREATEFIGURE(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6, cdata7, cdata8, cdata9, cdata10, cdata11, cdata12, cdata13, cdata14, cdata15, cdata16, cdata17, cdata18, cdata19, cdata20, cdata21, cdata22, cdata23, cdata24, cdata25, cdata26, cdata27, cdata28, cdata29, cdata30, cdata31, cdata32, cdata33, cdata34, cdata35, cdata36, cdata37, cdata38, cdata39, cdata40, cdata41, cdata42, cdata43, cdata44, cdata45, cdata46, cdata47, cdata48, cdata49, cdata50, cdata51, cdata52, cdata53)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata
%  CDATA7:  image cdata
%  CDATA8:  image cdata
%  CDATA9:  image cdata
%  CDATA10:  image cdata
%  CDATA11:  image cdata
%  CDATA12:  image cdata
%  CDATA13:  image cdata
%  CDATA14:  image cdata
%  CDATA15:  image cdata
%  CDATA16:  image cdata
%  CDATA17:  image cdata
%  CDATA18:  image cdata
%  CDATA19:  image cdata
%  CDATA20:  image cdata
%  CDATA21:  image cdata
%  CDATA22:  image cdata
%  CDATA23:  image cdata
%  CDATA24:  image cdata
%  CDATA25:  image cdata
%  CDATA26:  image cdata
%  CDATA27:  image cdata
%  CDATA28:  image cdata
%  CDATA29:  image cdata
%  CDATA30:  image cdata
%  CDATA31:  image cdata
%  CDATA32:  image cdata
%  CDATA33:  image cdata
%  CDATA34:  image cdata
%  CDATA35:  image cdata
%  CDATA36:  image cdata
%  CDATA37:  image cdata
%  CDATA38:  image cdata
%  CDATA39:  image cdata
%  CDATA40:  image cdata
%  CDATA41:  image cdata
%  CDATA42:  image cdata
%  CDATA43:  image cdata
%  CDATA44:  image cdata
%  CDATA45:  image cdata
%  CDATA46:  image cdata
%  CDATA47:  image cdata
%  CDATA48:  image cdata
%  CDATA49:  image cdata
%  CDATA50:  image cdata
%  CDATA51:  image cdata
%  CDATA52:  image cdata
%  CDATA53:  image cdata

%  Auto-generated by MATLAB on 26-May-2024 22:11:57

% Create figure
figure('InvertHardcopy','off','PaperUnits','normalized','Tag','Graphics',...
    'NumberTitle','off',...
    'Name','SPM12 (7771): Graphics',...
    'Color',[1 1 1]);
colormap(gray(64));

% Create axes
axes1 = axes('Tag','slice overlay panel',...
    'Position',[9 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes1,'on');

% Create image
image(cdata1);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-70',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 63]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes2 = axes('Tag','slice overlay panel',...
    'Position',[87 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes2,'on');

% Create image
image(cdata2);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-67',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1 63]);
box(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes3 = axes('Tag','slice overlay panel',...
    'Position',[165 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes3,'on');

% Create image
image(cdata3);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-64',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[1 63]);
box(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes4 = axes('Tag','slice overlay panel',...
    'Position',[243 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes4,'on');

% Create image
image(cdata4);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-61',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[1 63]);
box(axes4,'on');
hold(axes4,'off');
% Set the remaining axes properties
set(axes4,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes5 = axes('Tag','slice overlay panel',...
    'Position',[321 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes5,'on');

% Create image
image(cdata5);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-58',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[1 63]);
box(axes5,'on');
hold(axes5,'off');
% Set the remaining axes properties
set(axes5,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes6 = axes('Tag','slice overlay panel',...
    'Position',[399 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes6,'on');

% Create image
image(cdata6);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-55',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[1 63]);
box(axes6,'on');
hold(axes6,'off');
% Set the remaining axes properties
set(axes6,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes7 = axes('Tag','slice overlay panel',...
    'Position',[477 655.243018867925 78 92.7169811320755],...
    'Units','pixels');
hold(axes7,'on');

% Create image
image(cdata7);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-52',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[1 63]);
box(axes7,'on');
hold(axes7,'off');
% Set the remaining axes properties
set(axes7,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes8 = axes('Tag','slice overlay panel',...
    'Position',[9 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes8,'on');

% Create image
image(cdata8);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-49',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[1 63]);
box(axes8,'on');
hold(axes8,'off');
% Set the remaining axes properties
set(axes8,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes9 = axes('Tag','slice overlay panel',...
    'Position',[87 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes9,'on');

% Create image
image(cdata9);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-46',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[1 63]);
box(axes9,'on');
hold(axes9,'off');
% Set the remaining axes properties
set(axes9,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes10 = axes('Tag','slice overlay panel',...
    'Position',[165 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes10,'on');

% Create image
image(cdata10);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-43',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes10,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes10,[1 63]);
box(axes10,'on');
hold(axes10,'off');
% Set the remaining axes properties
set(axes10,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes11 = axes('Tag','slice overlay panel',...
    'Position',[243 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes11,'on');

% Create image
image(cdata11);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-40',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes11,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes11,[1 63]);
box(axes11,'on');
hold(axes11,'off');
% Set the remaining axes properties
set(axes11,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes12 = axes('Tag','slice overlay panel',...
    'Position',[321 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes12,'on');

% Create image
image(cdata12);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-37',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes12,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes12,[1 63]);
box(axes12,'on');
hold(axes12,'off');
% Set the remaining axes properties
set(axes12,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes13 = axes('Tag','slice overlay panel',...
    'Position',[399 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes13,'on');

% Create image
image(cdata13);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-34',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes13,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes13,[1 63]);
box(axes13,'on');
hold(axes13,'off');
% Set the remaining axes properties
set(axes13,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes14 = axes('Tag','slice overlay panel',...
    'Position',[477 562.526037735849 78 92.7169811320755],...
    'Units','pixels');
hold(axes14,'on');

% Create image
image(cdata14);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-31',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes14,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes14,[1 63]);
box(axes14,'on');
hold(axes14,'off');
% Set the remaining axes properties
set(axes14,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes15 = axes('Tag','slice overlay panel',...
    'Position',[9 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes15,'on');

% Create image
image(cdata15);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-28',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes15,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes15,[1 63]);
box(axes15,'on');
hold(axes15,'off');
% Set the remaining axes properties
set(axes15,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes16 = axes('Tag','slice overlay panel',...
    'Position',[87 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes16,'on');

% Create image
image(cdata16);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-25',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes16,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes16,[1 63]);
box(axes16,'on');
hold(axes16,'off');
% Set the remaining axes properties
set(axes16,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes17 = axes('Tag','slice overlay panel',...
    'Position',[165 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes17,'on');

% Create image
image(cdata17);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-22',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes17,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes17,[1 63]);
box(axes17,'on');
hold(axes17,'off');
% Set the remaining axes properties
set(axes17,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes18 = axes('Tag','slice overlay panel',...
    'Position',[243 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes18,'on');

% Create image
image(cdata18);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-19',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes18,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes18,[1 63]);
box(axes18,'on');
hold(axes18,'off');
% Set the remaining axes properties
set(axes18,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes19 = axes('Tag','slice overlay panel',...
    'Position',[321 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes19,'on');

% Create image
image(cdata19);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-16',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes19,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes19,[1 63]);
box(axes19,'on');
hold(axes19,'off');
% Set the remaining axes properties
set(axes19,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes20 = axes('Tag','slice overlay panel',...
    'Position',[399 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes20,'on');

% Create image
image(cdata20);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-13',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes20,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes20,[1 63]);
box(axes20,'on');
hold(axes20,'off');
% Set the remaining axes properties
set(axes20,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes21 = axes('Tag','slice overlay panel',...
    'Position',[477 469.809056603774 78 92.7169811320754],...
    'Units','pixels');
hold(axes21,'on');

% Create image
image(cdata21);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','-10',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes21,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes21,[1 63]);
box(axes21,'on');
hold(axes21,'off');
% Set the remaining axes properties
set(axes21,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes22 = axes('Tag','slice overlay panel',...
    'Position',[9 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes22,'on');

% Create image
image(cdata22);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' -7',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes22,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes22,[1 63]);
box(axes22,'on');
hold(axes22,'off');
% Set the remaining axes properties
set(axes22,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes23 = axes('Tag','slice overlay panel',...
    'Position',[87 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes23,'on');

% Create image
image(cdata23);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' -4',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes23,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes23,[1 63]);
box(axes23,'on');
hold(axes23,'off');
% Set the remaining axes properties
set(axes23,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes24 = axes('Tag','slice overlay panel',...
    'Position',[165 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes24,'on');

% Create image
image(cdata24);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' -1',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes24,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes24,[1 63]);
box(axes24,'on');
hold(axes24,'off');
% Set the remaining axes properties
set(axes24,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes25 = axes('Tag','slice overlay panel',...
    'Position',[243 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes25,'on');

% Create image
image(cdata25);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' +2',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes25,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes25,[1 63]);
box(axes25,'on');
hold(axes25,'off');
% Set the remaining axes properties
set(axes25,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes26 = axes('Tag','slice overlay panel',...
    'Position',[321 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes26,'on');

% Create image
image(cdata26);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' +5',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes26,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes26,[1 63]);
box(axes26,'on');
hold(axes26,'off');
% Set the remaining axes properties
set(axes26,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes27 = axes('Tag','slice overlay panel',...
    'Position',[399 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes27,'on');

% Create image
image(cdata27);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String',' +8',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes27,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes27,[1 63]);
box(axes27,'on');
hold(axes27,'off');
% Set the remaining axes properties
set(axes27,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes28 = axes('Tag','slice overlay panel',...
    'Position',[477 377.092075471698 78 92.7169811320755],...
    'Units','pixels');
hold(axes28,'on');

% Create image
image(cdata28);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+11',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes28,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes28,[1 63]);
box(axes28,'on');
hold(axes28,'off');
% Set the remaining axes properties
set(axes28,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes29 = axes('Tag','slice overlay panel',...
    'Position',[9 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes29,'on');

% Create image
image(cdata29);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+14',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes29,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes29,[1 63]);
box(axes29,'on');
hold(axes29,'off');
% Set the remaining axes properties
set(axes29,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes30 = axes('Tag','slice overlay panel',...
    'Position',[87 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes30,'on');

% Create image
image(cdata30);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+17',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes30,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes30,[1 63]);
box(axes30,'on');
hold(axes30,'off');
% Set the remaining axes properties
set(axes30,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes31 = axes('Tag','slice overlay panel',...
    'Position',[165 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes31,'on');

% Create image
image(cdata31);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+20',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes31,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes31,[1 63]);
box(axes31,'on');
hold(axes31,'off');
% Set the remaining axes properties
set(axes31,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes32 = axes('Tag','slice overlay panel',...
    'Position',[243 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes32,'on');

% Create image
image(cdata32);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+23',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes32,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes32,[1 63]);
box(axes32,'on');
hold(axes32,'off');
% Set the remaining axes properties
set(axes32,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes33 = axes('Tag','slice overlay panel',...
    'Position',[321 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes33,'on');

% Create image
image(cdata33);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+26',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes33,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes33,[1 63]);
box(axes33,'on');
hold(axes33,'off');
% Set the remaining axes properties
set(axes33,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes34 = axes('Tag','slice overlay panel',...
    'Position',[399 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes34,'on');

% Create image
image(cdata34);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+29',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes34,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes34,[1 63]);
box(axes34,'on');
hold(axes34,'off');
% Set the remaining axes properties
set(axes34,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes35 = axes('Tag','slice overlay panel',...
    'Position',[477 284.375094339623 78 92.7169811320755],...
    'Units','pixels');
hold(axes35,'on');

% Create image
image(cdata35);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+32',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes35,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes35,[1 63]);
box(axes35,'on');
hold(axes35,'off');
% Set the remaining axes properties
set(axes35,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes36 = axes('Tag','slice overlay panel',...
    'Position',[9 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes36,'on');

% Create image
image(cdata36);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+35',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes36,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes36,[1 63]);
box(axes36,'on');
hold(axes36,'off');
% Set the remaining axes properties
set(axes36,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes37 = axes('Tag','slice overlay panel',...
    'Position',[87 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes37,'on');

% Create image
image(cdata37);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+38',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes37,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes37,[1 63]);
box(axes37,'on');
hold(axes37,'off');
% Set the remaining axes properties
set(axes37,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes38 = axes('Tag','slice overlay panel',...
    'Position',[165 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes38,'on');

% Create image
image(cdata38);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+41',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes38,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes38,[1 63]);
box(axes38,'on');
hold(axes38,'off');
% Set the remaining axes properties
set(axes38,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes39 = axes('Tag','slice overlay panel',...
    'Position',[243 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes39,'on');

% Create image
image(cdata39);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+44',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes39,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes39,[1 63]);
box(axes39,'on');
hold(axes39,'off');
% Set the remaining axes properties
set(axes39,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes40 = axes('Tag','slice overlay panel',...
    'Position',[321 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes40,'on');

% Create image
image(cdata40);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+47',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes40,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes40,[1 63]);
box(axes40,'on');
hold(axes40,'off');
% Set the remaining axes properties
set(axes40,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes41 = axes('Tag','slice overlay panel',...
    'Position',[399 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes41,'on');

% Create image
image(cdata41);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+50',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes41,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes41,[1 63]);
box(axes41,'on');
hold(axes41,'off');
% Set the remaining axes properties
set(axes41,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes42 = axes('Tag','slice overlay panel',...
    'Position',[477 191.658113207547 78 92.7169811320755],...
    'Units','pixels');
hold(axes42,'on');

% Create image
image(cdata42);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+53',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes42,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes42,[1 63]);
box(axes42,'on');
hold(axes42,'off');
% Set the remaining axes properties
set(axes42,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes43 = axes('Tag','slice overlay panel',...
    'Position',[9 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes43,'on');

% Create image
image(cdata43);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+56',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes43,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes43,[1 63]);
box(axes43,'on');
hold(axes43,'off');
% Set the remaining axes properties
set(axes43,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes44 = axes('Tag','slice overlay panel',...
    'Position',[87 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes44,'on');

% Create image
image(cdata44);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+59',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes44,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes44,[1 63]);
box(axes44,'on');
hold(axes44,'off');
% Set the remaining axes properties
set(axes44,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes45 = axes('Tag','slice overlay panel',...
    'Position',[165 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes45,'on');

% Create image
image(cdata45);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+62',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes45,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes45,[1 63]);
box(axes45,'on');
hold(axes45,'off');
% Set the remaining axes properties
set(axes45,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes46 = axes('Tag','slice overlay panel',...
    'Position',[243 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes46,'on');

% Create image
image(cdata46);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+65',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes46,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes46,[1 63]);
box(axes46,'on');
hold(axes46,'off');
% Set the remaining axes properties
set(axes46,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes47 = axes('Tag','slice overlay panel',...
    'Position',[321 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes47,'on');

% Create image
image(cdata47);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+68',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes47,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes47,[1 63]);
box(axes47,'on');
hold(axes47,'off');
% Set the remaining axes properties
set(axes47,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes48 = axes('Tag','slice overlay panel',...
    'Position',[399 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes48,'on');

% Create image
image(cdata48);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+71',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes48,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes48,[1 63]);
box(axes48,'on');
hold(axes48,'off');
% Set the remaining axes properties
set(axes48,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes49 = axes('Tag','slice overlay panel',...
    'Position',[477 98.9411320754717 78 92.7169811320755],...
    'Units','pixels');
hold(axes49,'on');

% Create image
image(cdata49);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+74',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes49,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes49,[1 63]);
box(axes49,'on');
hold(axes49,'off');
% Set the remaining axes properties
set(axes49,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes50 = axes('Tag','slice overlay panel',...
    'Position',[9 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');
hold(axes50,'on');

% Create image
image(cdata50);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+77',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes50,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes50,[1 63]);
box(axes50,'on');
hold(axes50,'off');
% Set the remaining axes properties
set(axes50,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes51 = axes('Tag','slice overlay panel',...
    'Position',[87 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');
hold(axes51,'on');

% Create image
image(cdata51);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+80',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes51,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes51,[1 63]);
box(axes51,'on');
hold(axes51,'off');
% Set the remaining axes properties
set(axes51,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes52 = axes('Tag','slice overlay panel',...
    'Position',[165 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');
hold(axes52,'on');

% Create image
image(cdata52);

% Create text
text('VerticalAlignment','bottom','FontSize',0.075,'FontUnits','normalized',...
    'String','+83',...
    'Position',[1 1 0],...
    'Color',[1 1 1]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes52,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes52,[1 63]);
box(axes52,'on');
hold(axes52,'off');
% Set the remaining axes properties
set(axes52,'XTick',[],'XTickLabel','','YTick',[],'YTickLabel','');
% Create axes
axes53 = axes('Tag','slice overlay panel',...
    'Position',[243 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes53,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes53,[1 63]);
box(axes53,'on');
% Set the remaining axes properties
set(axes53,'Color',[0 0 0],'XTick',[],'XTickLabel','','YTick',[],...
    'YTickLabel','');
% Create axes
axes54 = axes('Tag','slice overlay panel',...
    'Position',[321 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes54,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes54,[1 63]);
box(axes54,'on');
% Set the remaining axes properties
set(axes54,'Color',[0 0 0],'XTick',[],'XTickLabel','','YTick',[],...
    'YTickLabel','');
% Create axes
axes55 = axes('Tag','slice overlay panel',...
    'Position',[399 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes55,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes55,[1 63]);
box(axes55,'on');
% Set the remaining axes properties
set(axes55,'Color',[0 0 0],'XTick',[],'XTickLabel','','YTick',[],...
    'YTickLabel','');
% Create axes
axes56 = axes('Tag','slice overlay panel',...
    'Position',[477 6.22415094339624 78 92.7169811320755],...
    'Units','pixels');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes56,[1 53]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes56,[1 63]);
box(axes56,'on');
% Set the remaining axes properties
set(axes56,'Color',[0 0 0],'XTick',[],'XTickLabel','','YTick',[],...
    'YTickLabel','');
% Create axes
axes57 = axes('Tag','cbar',...
    'Position',[508.2 17.8137735849057 15.6 69.5377358490566],...
    'Units','pixels');
hold(axes57,'on');

% Create image
image(1,[0 15.9278430938721],cdata53);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes57,[0 15.9278430938721]);
hold(axes57,'off');
% Set the remaining axes properties
set(axes57,'FontSize',0.075,'FontUnits','normalized','XTick',[],...
    'XTickLabel','','YColor',[1 1 1]);
